---
- hosts: 127.0.0.1
  connection: local
  tasks:

    - name: "update homebrew"
      homebrew: update_homebrew=yes

    - name: "install homebrew taps"
      homebrew_tap: tap={{ item }} state=present
      with_items:
        - caskroom/cask
        - neovim/neovim

    - name: "install homebrew apps"
      homebrew: name={{ item }} state=present
      with_items:
        - ag
        - bitlbee
        - byobu # this also installs tmux
        - coreutils
        - diff-so-fancy
        - docker
        - entr
        - irssi
        - mpd
        - mpv
        - neovim
        - ncmpc
        - node
        - p7zip
        - pow
        - ranger
        - tig
        - tree
        - zsh

    - name: "install homebrew casks"
      homebrew_cask: name={{ item }} state=present
      with_items:
        - caffeine
        - google-chrome
        - iterm2
        - lastpass
        - slack
        - spotify
        - vagrant

    - name: "upgrade all homebrew installs"
      homebrew: upgrade_all=yes

    - block: # enable zsh

      - name: "check for homebrew zsh in /etc/shells"
        register: zsh_enabled
        shell: cat /etc/shells | grep /usr/local/bin/zsh | wc -l
        changed_when: false

      - name: "add homebrew zsh to /etc/shells"
        when: zsh_enabled.stdout == "0"
        become: true
        shell: echo "/usr/local/bin/zsh" >> /etc/shells

      - name: "chsh to zsh"
        when: ansible_env.SHELL != "/usr/local/bin/zsh"
        command: /usr/bin/chsh -s /usr/local/bin/zsh
