---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: "update homebrew"
      homebrew: update_homebrew=yes

    - name: "install homebrew taps"
      homebrew_tap: tap={{ item }} state=present
      with_items:
        - caskroom/cask
        - caskroom/versions
        - homebrew/games
        - neovim/neovim

    - name: "install homebrew apps"
      homebrew: name={{ item }} state=present
      with_items:
        - ag
        - awscli
        - bitlbee
        - byobu # this also installs tmux
        - ccat
        - clib
        - coreutils
        - diff-so-fancy
        - docker
        - docker-compose
        - docker-machine
        - entr
        - fswatch
        - fzf
        - gcal
        - git
        - hub
        - irssi
        - mpd
        - mpv
        - neovim
        - ncmpc
        - nvm
        - p7zip
        - pow
        - ranger
        - tig
        - tree
        - wget
        - zsh

    - name: "install homebrew tty games"
      homebrew: name={{ item }} state=present
      with_items:
        - angband
        - avanor
        - brogue
        - curseofwar
        - nethack4
        - nudoku
        - omega-rpg
        - roll
        - stone-soup

    - name: "install homebrew casks"
      homebrew_cask: name={{ item }} state=present
      with_items:
        - alfred
        - atext
        - bartender
        - bettertouchtool
        - dash
        - disk-inventory-x
        - fastscripts
        - google-chrome
        - gpgtools
        - hammerspoon
        - honer
        - iterm2-beta
        - itsycal
        - lastpass
        - macclean
        - nylas-n1
        - phoenix
        - screenhero
        - slack
        - spotify
        - ubersicht
        - vagrant
        - virtualbox
        - viscosity
        - zoomus

    - name: "upgrade all homebrew installs"
      homebrew: upgrade_all=yes
