---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: "update homebrew"
      homebrew: update_homebrew=yes

    - name: "install homebrew taps"
      homebrew_tap: tap={{ item }} state=present
      with_items:
        - caskroom/cask
        - caskroom/versions
        - neovim/neovim

    - name: "install homebrew apps"
      homebrew: name={{ item }} state=present
      with_items:
        - ag
        - bitlbee
        - byobu # this also installs tmux
        - ccat
        - coreutils
        - diff-so-fancy
        - docker
        - docker-compose
        - docker-machine
        - entr
        - fzf
        - git
        - irssi
        - mpd
        - mpv
        - neovim
        - ncmpc
        - nvm
        - p7zip
        - pow
        - ranger
        - tig
        - tree
        - zsh

    - name: "install homebrew casks"
      homebrew_cask: name={{ item }} state=present
      with_items:
        - alfred
        - bartender
        - bettertouchtool
        - caffeine
        - dash
        - disk-inventory-x
        - fastscripts
        - google-chrome
        - gpgtools
        - iterm2-beta
        - itsycal
        - lastpass
        - macclean
        - nylas-n1
        - slack
        - spotify
        - textexpander
        - vagrant
        - virtualbox
        - viscosity

    - name: "upgrade all homebrew installs"
      homebrew: upgrade_all=yes
