---
- hosts: 127.0.0.1
  connection: local
  tasks:

    - name: "gather $XDG_CONFIG_HOME dotfiles"
      shell: ls -d -1 {{ playbook_dir }}/../../files/dotfiles/xdg_config/* | xargs realpath
      register: xdg_dotfiles
      changed_when: false

    - name: "symlink $XDG_CONFIG_HOME dotfiles"
      file: state=link
            src={{ item }}
            dest={{ xdg_config }}/{{ item | basename }}
      with_items: "{{ xdg_dotfiles.stdout_lines }}"
